# This is a config for E2B sandbox template.
# You can use template ID (lrna86bv1kbj90m7svbk) or template name (vibe-nextjs-wahyuramaa) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-wahyuramaa") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-wahyuramaa") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-wahyuramaa')

team_id = "879a191e-bda4-47eb-906c-8f349279659e"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-wahyuramaa"
template_id = "lrna86bv1kbj90m7svbk"
